#! /bin/sh

SCHEDULER=/usr/sbin/icecc-scheduler
CONFIGFILE=/etc/icecc/icecc.conf
DEFAULTFILE=/etc/default/icecc

# Read configuration files
[ -r $CONFIGFILE ] && . $CONFIGFILE
[ -r $DEFAULTFILE ] && . $DEFAULTFILE

test -x $SCHEDULER || exit 0

params=""

if test -n "$ICECC_NETNAME"; then
    params="$params -n $ICECC_NETNAME"
fi

if test -z "$ICECC_SCHEDULER_LOG_FILE"; then
    ICECC_SCHEDULER_LOG_FILE="/var/log/icecc_scheduler"
fi

if test -n "$ICECC_SCHEDULER_LOG_FILE"; then
    params="$params -l $ICECC_SCHEDULER_LOG_FILE"
fi

if test -n "$ICECC_SCHEDULER_ALGORITHM"; then
    params="$params -a $ICECC_SCHEDULER_ALGORITHM"
fi

if test -n "$ICECC_VERBOSE"; then
    params="$params $ICECC_VERBOSE"
fi

exec $SCHEDULER $params "$@"