#! /bin/sh

DAEMON=/usr/sbin/iceccd
CONFIGFILE=/etc/icecc/icecc.conf
DEFAULTFILE=/etc/default/icecc

# Read configuration files
[ -r $CONFIGFILE ] && . $CONFIGFILE
[ -r $DEFAULTFILE ] && . $DEFAULTFILE

test -x $DAEMON || exit 0

params=""

if test -n "$ICECC_NETNAME"; then
    params="$params -n $ICECC_NETNAME"
fi

if test -n "$ICECC_LOG_FILE"; then
    params="$params -l $ICECC_LOG_FILE"
fi

if test -n "$ICECC_NICE_LEVEL"; then
    params="$params --nice $ICECC_NICE_LEVEL"
fi

if test -n "$ICECC_SCHEDULER_HOST"; then
    params="$params -s $ICECC_SCHEDULER_HOST"
fi

if test -n "$ICECC_BASEDIR"; then
    params="$params -b $ICECC_BASEDIR"
fi

if test "$ICECC_ALLOW_REMOTE" = "no" 2> /dev/null; then
        params="$params --no-remote"
fi

if test -n "$ICECC_MAX_JOBS"; then
    if test "$ICECC_MAX_JOBS" -eq 0 2> /dev/null; then
        params="$params -m 1 --no-remote"
    else
        params="$params -m $ICECC_MAX_JOBS"
    fi
fi

if test -n "$ICECC_CACHE_LIMIT"; then
        params="$params --cache-limit $ICECC_CACHE_LIMIT"
fi

if test -n "$ICECC_VERBOSE"; then
        params="$params $ICECC_VERBOSE"
fi

exec $DAEMON $@ $params
