debian/icecc.conf etc/icecc/
debian/iceccd-wrapper usr/bin/iceccd-wrapper
debian/icecc-scheduler-wrapper usr/sbin/icecc-scheduler-wrapper
debian/iceccd.service lib/systemd/system/iceccd.service
debian/icecc-scheduler.service lib/systemd/system/icecc-scheduler.service
usr/bin/icecc
usr/bin/icecc-create-env
usr/bin/icecc-test-env
usr/bin/icerun
usr/lib/icecc/bin/c++
usr/lib/icecc/bin/cc
usr/lib/icecc/bin/clang
usr/lib/icecc/bin/clang++
usr/lib/icecc/bin/g++
usr/lib/icecc/bin/gcc
usr/lib/icecc/compilerwrapper
usr/lib/icecc/icecc-create-env
usr/sbin/icecc-scheduler
usr/sbin/iceccd
usr/share/man/man1/icecc-create-env.1
usr/share/man/man1/icecc-scheduler.1
usr/share/man/man1/icecc.1
usr/share/man/man1/iceccd.1
usr/share/man/man1/icerun.1
usr/share/man/man7/icecream.7
